from typing import List

from dotenv import load_dotenv

from langchain.tools import tool
from langchain.agents import create_agent
from langchain.messages import HumanMessage, AIMessage, SystemMessage
from langchain_tavily import TavilySearch

from pydantic import BaseModel, Field

load_dotenv()


# Defining Structured Output Response
class Source(BaseModel):
    """Class for the original source that verifies the generated response"""

    url: str = Field(description="The url for the original source.")


class AIResponse(BaseModel):
    """Class that contains the agent's generated response along with a list of the sources that the users can use to verify the responses."""

    response: str = Field(
        description="The response generated by the AI regards to the user's query."
    )
    sources: List[Source] = Field(
        default_factory=List,
        description="A list of sources that verifies the model's claimed responses.",
    )


# Defining a tool
# Note: This is just to showcase how to write a custom function (including the docstring)
# However, the optimal practice should be just using the SDK's built-in search tool.
@tool
def search(query: str):
    """Tool that seraches over internet
    Args:
        query: The query to search for
    Returns:
        The search result
    """
    print(f"Searching for {query}")
    tavily_search = TavilySearch(max_results=5, topic="general")
    return tavily_search.invoke({"query": query})


# Setup the agent
tools = [search]
messages = [
    HumanMessage(
        "List out 3 job postings that are still open now that require an AI engineer with knowledge on langchain in Selangor, Malaysia"
    )
]
llm = create_agent(
    model="openai:gpt-5.4-mini",
    tools=tools,
    system_prompt="You are a helpful assistant that answer user's question amicably.",
    response_format=AIResponse,
)


def main():
    print("Hello from 2-0-search-agent!")

    """If the output is not structured, i.e. no response_format"""
    # Call the agent into action
    response = llm.invoke({"messages": messages})

    # View the result

    """If the output is not structured, i.e. no response_format"""
    # print(response["messages"][-1].content)

    """ If the output is structured, require response_format """
    print(response["structured_response"])


if __name__ == "__main__":
    main()
